### ISSUE TITLE
运行Log4jAppenderExample  抛异常

### ISSUE THREAD

**Issue by pingqiang806796422** [aliyun/aliyun-log-log4j-appender#10]
SLF4J: A number (1) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
log4j:ERROR Failed to send log, project=jxmj-v1, logStore=jxmj-v1, topic=, source=, logItem=com.aliyun.openservices.log.common.LogItem@3252ea7c
java.lang.IllegalStateException: cannot append after the log accumulator was closed
	at com.aliyun.openservices.aliyun.log.producer.internals.LogAccumulator.doAppend(LogAccumulator.java:95)
	at com.aliyun.openservices.aliyun.log.producer.internals.LogAccumulator.append(LogAccumulator.java:79)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:356)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:279)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:240)
	at com.aliyun.openservices.log.log4j.LoghubAppender.append(LoghubAppender.java:127)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.info(Log4jLoggerAdapter.java:305)
	at org.slf4j.helpers.SubstituteLogger.info(SubstituteLogger.java:169)
	at com.aliyun.openservices.aliyun.log.producer.internals.RetryQueue.expiredBatches(RetryQueue.java:53)
	at com.aliyun.openservices.aliyun.log.producer.internals.Mover.doMoveBatches(Mover.java:87)
	at com.aliyun.openservices.aliyun.log.producer.internals.Mover.moveBatches(Mover.java:73)
	at com.aliyun.openservices.aliyun.log.producer.internals.Mover.loopMoveBatches(Mover.java:63)
	at com.aliyun.openservices.aliyun.log.producer.internals.Mover.run(Mover.java:52)
log4j:ERROR Failed to send log, project=jxmj-v1, logStore=jxmj-v1, topic=, source=, logItem=com.aliyun.openservices.log.common.LogItem@614041cd
java.lang.IllegalStateException: cannot append after the log accumulator was closed
	at com.aliyun.openservices.aliyun.log.producer.internals.LogAccumulator.doAppend(LogAccumulator.java:95)
	at com.aliyun.openservices.aliyun.log.producer.internals.LogAccumulator.append(LogAccumulator.java:79)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:356)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:279)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.send(LogProducer.java:240)

**Comment by chaolee50** [comment]
fixed

**Comment by pingqiang806796422** [comment]
?

**Comment by chaolee50** [comment]
> ?

你好，更新一下代码，运行Example还有问题吗

**Comment by pingqiang806796422** [comment]
最近没有空搞日志了，有空试了在反馈吧，谢谢

**Comment by chaolee50** [comment]
好的
