### ISSUE TITLE
tomcat每次重启都会报错

### ISSUE THREAD

**Issue by lhqiang** [aliyun/aliyun-log-log4j-appender#5]
tomcat启动时报错如下：
30-Jul-2018 23:03:40.871 INFO [log-producer-control-worker-0] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.aliyun.openservices.log.producer.inner.BlockedData]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.aliyun.openservices.log.producer.inner.BlockedData]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
        at com.aliyun.openservices.log.producer.inner.IOThread.addPackage(IOThread.java:76)
        at com.aliyun.openservices.log.producer.inner.PackageManager.filterTimeoutPackage(PackageManager.java:74)
        at com.aliyun.openservices.log.producer.inner.ControlThreadPool$1.run(ControlThreadPool.java:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by brucewu-fly** [comment]
@lhqiang  出现这个错误一般是因为之前的tomcat中的线程还没有完全关闭。尝试把 reloadable 参数设为 false。
