### ISSUE TITLE
日志量比较大，一直报这个错

### ISSUE THREAD

**Issue by zczhzy** [aliyun/aliyun-log-log4j-appender#8]
`log4j:ERROR Failed to putLogs. project=item-server logstore=access-log topic= source= logItems=[com.aliyun.openservices.log.common.LogItem@1fa921f7]
com.aliyun.openservices.log.exception.LogException: denied by sts or ram, action: log:PostLogStoreLogs, resource: acs:log:cn-hangzhou:1530704xxxxx:project/itemxxxx/logstore/accessxxxx, itemscount: 243
	at com.aliyun.openservices.log.producer.inner.IOThread.doSendData(IOThread.java:180)
	at com.aliyun.openservices.log.producer.inner.IOThread.sendData(IOThread.java:126)
	at com.aliyun.openservices.log.producer.inner.IOThread.access$000(IOThread.java:38)
	at com.aliyun.openservices.log.producer.inner.IOThread$1.run(IOThread.java:225)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by brucewu-fly** [comment]
您好
这是资源不足引起的，您可以尝试增加 logstore 的 shard 个数。
https://help.aliyun.com/document_detail/86660.html
